### ISSUE TITLE
ConnectionError: Name request has failed: 2

### ISSUE THREAD

**Issue by cradcore** [Rudd-O/hassmpris_agent#6]
I am running a minimal Debian install without a DE for my HTPC using x11 and openbox for apps. When attempting to run the agent, I get the following:
```
$ hassmpris-agent
INFO:hassmpris_agent.server:Loading / creating CA certificates.
INFO:hassmpris_agent.server:Loading / creating server certificates.
INFO:hassmpris_agent.server:Creating server.
DEBUG:asyncio:Using selector: EpollSelector
INFO:hassmpris_agent.server:Starting server.
DEBUG:dasbus.connection:Publishing an object at /.
INFO:dasbus.connection:Connecting to the session bus.
INFO:dasbus.connection:Connecting to the session bus.
DEBUG:dasbus.connection:Registering a service name com.rudd_o.HASSMPRIS1.
Traceback (most recent call last):
  File "/usr/local/bin/hassmpris-agent", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/hassmpris_agent/server.py", line 122, in main
    agent.start()
  File "/usr/local/lib/python3.11/dist-packages/hassmpris_agent/server.py", line 76, in start
    self.dbus_control_iface.start()
  File "/usr/local/lib/python3.11/dist-packages/hassmpris_agent/control.py", line 44, in start
    bus.register_service("com.rudd_o.HASSMPRIS1")
  File "/usr/local/lib/python3.11/dist-packages/dasbus/connection.py", line 262, in register_service
    raise ConnectionError("Name request has failed: {}".format(result))
ConnectionError: Name request has failed: 2
```

Seems like a problem with the dbus connection, although the dbus service is active and running. Any ideas?

**Comment by Rudd-O** [comment]
Maybe you already have a second copy running?  Please check your session bus with `qdbus`.

**Comment by Rudd-O** [comment]
I may need more extensive logging from your system journal.
